### ISSUE TITLE
Rakarrack 0.6.1-4build2  have Segmentation fault  on 18.04

### ISSUE THREAD

**Issue by MGdesigner** [KXStudio/Repository#182]
I tested Rakarrack 0.6.1-4build2 both on 16.04 and 18.04.  It works on 16.04,but crashed on 18.04. I found there is also [a similar report ](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892077)about this on Debian. I use gdb to check ,but it is different on Thread 1.

------------------
(gdb) run
Starting program: /usr/bin/rakarrack 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

rakarrack 0.6.1 - Copyright (c) Josep Andreu - Ryan Billing - Douglas McClendon - Arnout Engelen
Try 'rakarrack --help' for command-line options.
[New Thread 0x7ffff7fb9700 (LWP 2994)]
[New Thread 0x7ffff7f38700 (LWP 2995)]

Thread 1 "rakarrack" received signal SIGSEGV, Segmentation fault.
0x00005555555ebbd0 in ?? ()
(gdb) thread apply all bt

Thread 3 (Thread 0x7ffff7f38700 (LWP 2995)):
#0  0x00007ffff71cb384 in __libc_read (fd=5, buf=0x7ffff7f37cc0, nbytes=4)
    at ../sysdeps/unix/sysv/linux/read.c:27
#1  0x00007ffff6c92b95 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#2  0x00007ffff6c9693c in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#3  0x00007ffff6c913b0 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#4  0x00007ffff71c16db in start_thread (arg=0x7ffff7f38700)
    at pthread_create.c:463
#5  0x00007ffff5a6388f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7ffff7fb9700 (LWP 2994)):
#0  0x00007ffff71c79f3 in futex_wait_cancelable (private=<optimized out>, 
    expected=0, futex_word=0x5555558692d8)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x555555869280, 
    cond=0x5555558692b0) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x5555558692b0, mutex=0x555555869280)
    at pthread_cond_wait.c:655
#3  0x00007ffff6c921dc in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#4  0x00007ffff6c84f08 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#5  0x00007ffff6c913b0 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
---Type <return> to continue, or q <return> to quit---
#6  0x00007ffff71c16db in start_thread (arg=0x7ffff7fb9700)
    at pthread_create.c:463
#7  0x00007ffff5a6388f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7ffff7fba7c0 (LWP 2990)):
#0  0x00005555555ebbd0 in ?? ()
#1  0x00005555555ebde1 in ?? ()
#2  0x00005555555bebfd in ?? ()
#3  0x0000555555569a92 in ?? ()
#4  0x00007ffff5963b97 in __libc_start_main (main=0x5555555698d0, argc=1, 
    argv=0x7fffffffddf8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffdde8)
    at ../csu/libc-start.c:310
#5  0x0000555555569dea in ?? ()

**Comment by falkTX** [comment]
That package comes from debian, not KXStudio.
At some point kxstudio had a custom rakarrack package, not sure what happened.. likely on the old repos, and never got pushed to the "new" ones 4 years ago.

**Comment by MGdesigner** [comment]
I see. Hope  KXstudio will build a new one . :)
